const path = require('path');
const fs = require('fs-extra');
const yaml = require('js-yaml');
const Generator = require('../core/generator');
const AssetManager = require('../core/asset');
const processor = require('../core/processor');
const { readDirRecursive, exists, emptyDir, ensureDir } = require('../utils/file');

/**
 * 构建命令
 */
async function build() {
  console.log('WDR Build Started...');
  console.log('====================\n');

  const startTime = Date.now();

  try {
    // 1. 加载配置文件
    const config = await loadConfig();

    // 2. 检查源目录
    const sourceDir = path.resolve(config.source_dir || 'source');
    const postsDir = path.join(sourceDir, '_posts');

    if (!await exists(postsDir)) {
      console.log(`No posts directory found at ${postsDir}`);
      console.log('Creating sample posts directory...');
      await ensureDir(postsDir);
    }

    // 3. 清理并创建输出目录
    const publicDir = path.resolve(config.public_dir || 'public');
    console.log(`Cleaning public directory: ${publicDir}`);
    await emptyDir(publicDir);

    // 4. 扫描 Markdown 文件
    console.log('\nScanning posts...');
    const files = await readDirRecursive(postsDir);
    console.log(`Found ${files.length} post(s)`);

    if (files.length === 0) {
      console.log('\nNo posts found. Creating a sample post...');
      const { init } = require('./init');
      // 只创建示例文章，不重新初始化
    }

    // 5. 解析文章
    console.log('\nProcessing posts...');
    const articles = await processor.parseMultiple(files);
    console.log(`Processed ${articles.length} article(s)`);

    if (articles.length > 0) {
      // 6. 确定主题路径
      const themePath = path.join(__dirname, '../../themes/default');

      // 7. 生成 HTML 页面
      console.log('\nGenerating pages...');
      const generator = new Generator(config, themePath);
      await generator.generate(articles);

      // 8. 复制静态资源
      console.log('\nCopying assets...');
      const assetManager = new AssetManager(config, themePath);
      await assetManager.copyAll();

      // 9. 生成路由信息
      const categories = processor.groupByCategory(articles);
      const tags = processor.groupByTag(articles);
      const Router = require('../core/router');
      const router = new Router(config);
      const routes = router.generateAll(articles, categories, tags);
      console.log(`Generated ${routes.length} route(s)`);

      const endTime = Date.now();
      const duration = ((endTime - startTime) / 1000).toFixed(2);

      console.log('\n====================');
      console.log(`✓ Build completed in ${duration}s!`);
      console.log(`Output: ${publicDir}`);
      console.log('\nRun "wdr server" to preview your site');

    } else {
      console.log('\n⚠ No articles to generate');
      console.log('Add some Markdown files to source/_posts/ and run "wdr build" again');
    }

  } catch (error) {
    console.error('\n✗ Build failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

/**
 * 加载配置文件
 */
async function loadConfig() {
  const configPath = path.resolve('_config.yml');

  if (!await exists(configPath)) {
    console.log('No _config.yml found, using default configuration');
    return getDefaultConfig();
  }

  try {
    const content = await fs.readFile(configPath, 'utf-8');
    const config = yaml.load(content);

    // 合并默认配置
    return { ...getDefaultConfig(), ...config };
  } catch (error) {
    console.error('Failed to load _config.yml:', error.message);
    return getDefaultConfig();
  }
}

/**
 * 获取默认配置
 */
function getDefaultConfig() {
  return {
    title: 'My Blog',
    subtitle: 'Powered by WDR',
    description: 'A static blog generated by WDR',
    author: 'Anonymous',
    language: 'zh-CN',
    timezone: 'Asia/Shanghai',
    url: '',
    root: '/',
    source_dir: 'source',
    public_dir: 'public',
    per_page: 10,
    theme: 'default',
    date_format: 'YYYY-MM-DD HH:mm:ss'
  };
}

module.exports = build;
